{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "company-trust-index.fullname" . }}
    labels:
        {{- include "company-trust-index.labels" . | nindent 8 }}
    {{- with .Values.ingress.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
    {{- with .Values.ingress.className }}
    ingressClassName: {{ . }}
    {{- end }}
    {{- with .Values.ingress.tls }}
    tls:
        {{- toYaml . | nindent 8 }}
    {{- else }}
    tls:
        - hosts:
              - {{ (index .Values.ingress.hosts 0).host | quote }}
          secretName: {{ include "company-trust-index.fullname" . }}-tls
    {{- end }}
    rules:
        {{- range .Values.ingress.hosts }}
        - host: {{ .host | quote }}
          http:
              paths:
                  {{- range .paths }}
                  - path: {{ .path }}
                    pathType: {{ .pathType }}
                    backend:
                        service:
                            name: {{ include "company-trust-index.fullname" $ }}
                            port:
                                name: http
                  {{- end }}
        {{- end }}
{{- end }}
