apiVersion: v1
kind: Service
metadata:
    name: {{ include "company-trust-index.fullname" . }}
    labels:
        {{- include "company-trust-index.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.targetPort }}
          protocol: TCP
          name: http
    selector:
        {{- include "company-trust-index.selectorLabels" . | nindent 8 }}
