
services:
  app:
    build:
      context: .
    image: ghcr.io/srah/company-trust-index:latest
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET: local-development-secret
      DATABASE_URL: mysql://app:!ChangeMe!@database:3306/app?serverVersion=mariadb-10.11.2&charset=utf8mb4
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:80"

  database:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}
      MARIADB_USER: ${MARIADB_USER:-app}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mariadb_data:/var/lib/mysql:rw

volumes:
  mariadb_data:
