apiVersion: v2
name: company-trust-index
description: Helm chart for the CompanyTrustIndex Symfony application
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://github.com/sRaH/company-trust-index
sources:
    - https://github.com/sRaH/company-trust-index
